#
# Copyright (C) 2026 The Android Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

# Platform & Kernel Info
BOARD_HAS_MTK_HARDWARE := true
TARGET_BOARD_PLATFORM := mt6768
TARGET_BOOTLOADER_BOARD_NAME := mt6769

# Header Boot Image
BOARD_BOOTIMG_HEADER_VERSION := 4
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)

# Konfigurasi Partisi Dynamic
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_PARTITION_LIST := system system_ext vendor product odm

# Pengaturan Enkripsi Data
BOARD_USES_METADATA_ENCRYPTION := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Resolusi Layar
TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1576

# TWRP Configuration Flags
TW_THEME := portrait_hd_resizable
TW_EXTRA_LANGUAGES := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true

# Vendor Boot Config (Modern MTK)
BOARD_USES_RECOVERY_AS_BOOT := false
TARGET_NO_RECOVERY := true
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 134217728 # 128MB (Standard Aman)
