name: Build OrangeFox Resmi Infinix X6840

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Device Tree Lo
      uses: actions/checkout@v4
      with:
        path: device/infinix/X6840

    - name: Install Panduan Build Sistem Modern
      run: |
        sudo apt-get update
        sudo apt-get install -y gperf gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc bison build-essential ccache curl flex g++ python3 openjdk-11-jdk

    - name: Ambil dan Jalankan Alat Sync Resmi OrangeFox
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        
        # Bikin folder sync sesuai petunjuk wiki
        mkdir ~/OrangeFox_sync
        cd ~/OrangeFox_sync
        
        # Clone script sync resmi dari github mirror agar lolos autentikasi
        git clone https://github.com/OrangeFoxRecovery/sync.git
        cd sync
        
        # Jalankan sinkronisasi cabang 12.1 (Paling stabil untuk OrangeFox Android modern)
        ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1
        
        # Pindahkan folder device tree Infinix lo ke lokasi kompilasi yang benar
        mv $GITHUB_WORKSPACE/device ~/fox_12.1/device

    - name: Proses Compile Sesuai Standard Prosedur Wiki
      run: |
        cd ~/fox_12.1
        /bin/bash
        
        # EXPORT SEMUA VARIABEL ORANGEFOX DI SINI (Sesuai Aturan Wiki)
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_BUILD_DEVICE=X6840
        export LC_ALL="C"
        
        # Fitur optimasi kompilasi MediaTek non-Xiaomi
        export FOX_VANILLA_BUILD=1
        export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=true
        export FOX_REPLACE_BUSYBOX_FOR_TWRP=true
        export FOX_USE_BASH_SHELL=true
        export FOX_ASH_IS_BASH=true
        export FOX_DRASTIC_SIZE_REDUCTION=1
        
        # Mulai proses kompilasi resmi OrangeFox
        source build/envsetup.sh
        lunch twrp_X6840-eng && mka adbd recoveryimage

    - name: Upload Hasil OrangeFox Zip + Img Matang
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-Infinix-X6840-Matang
        path: |
          ~/fox_12.1/out/target/product/X6840/OrangeFox-*.img
          ~/fox_12.1/out/target/product/X6840/OrangeFox-*.zip
          
