name: Build OrangeFox - Infinix X6840

on:
  workflow_dispatch:
    inputs:
      DEVICE_TREE:
        description: 'Link GitHub Device Tree'
        required: true
        default: 'https://github.com/KINGUSER/android_device_infinix_X6840'
      DEVICE_BRANCH:
        description: 'Branch Device Tree'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Persiapan
      run: |
        sudo apt update && sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc
        
    - name: Sinkronisasi
      run: |
        mkdir -p /home/runner/fox_12.1
        git clone https://gitlab.com/OrangeFox/sync.git /home/runner/sync_temp
        cd /home/runner/sync_temp
        ./orangefox_sync.sh --branch 12.1 --path /home/runner/fox_12.1

    - name: Kompilasi
      run: |
        cd /home/runner/fox_12.1
        mkdir -p device/infinix/X6840
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_BRANCH }} device/infinix/X6840
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_X6840-eng
        mka adbd recoveryimage

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-X6840
        path: /home/runner/fox_12.1/out/target/product/X6840/OrangeFox-*.img
